2025-05-23 19:52:16,916 - spizarnia - INFO - Database tables created successfully
2025-05-23 19:55:40,888 - spizarnia - INFO - Database tables created successfully
2025-05-23 19:55:40,888 - spizarnia - INFO - Application started successfully
2025-05-23 20:09:20,933 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:10:45,149 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:10:45,150 - spizarnia - INFO - Application started successfully
2025-05-23 20:11:54,461 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:11:54,462 - spizarnia - INFO - Application started successfully
2025-05-23 20:12:34,391 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:12:34,392 - spizarnia - INFO - Application started successfully
2025-05-23 20:15:53,236 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:15:53,236 - spizarnia - INFO - Application started successfully
2025-05-23 20:18:24,190 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:18:24,190 - spizarnia - INFO - Application started successfully
2025-05-23 20:20:25,875 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:20:25,875 - spizarnia - INFO - Application started successfully
2025-05-23 20:20:30,147 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:20:30,147 - spizarnia - INFO - Application started successfully
2025-05-23 20:22:24,968 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:22:24,968 - spizarnia - INFO - Application started successfully
2025-05-23 20:23:38,456 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:23:38,456 - spizarnia - INFO - Application started successfully
2025-05-23 20:24:39,399 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:24:39,399 - spizarnia - INFO - Application started successfully
2025-05-23 20:25:43,000 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:25:43,000 - spizarnia - INFO - Application started successfully
2025-05-23 20:26:19,889 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:26:19,889 - spizarnia - INFO - Application started successfully
2025-05-23 20:28:12,257 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:28:12,258 - spizarnia - INFO - Application started successfully
2025-05-23 20:29:07,388 - spizarnia - INFO - OCR (PDF) result for receipt 3: Hnuchan HIPERMARKET AUCHAN 05-270 WARSZAWA MARKI AL J .PIŁSUDSKIEGO 1 TEL (0-22) 444 02 22 AUCHAN POLSKA SP_ 2 0 . 0 . UL PUŁAWSKA 4 6 , 05-500 PIASECZNO WWW auchan.pl BDO 000013917 NIP 526-03-09-174
NIEFISKALNY
2025-03-04 ReWtymOplRec551061 1 x3 , 25 3 , 25A NAPOJ GAZ 86851A 1 x4 , 48 4 , 48A PAROWKI JAL 32107c 1   x6, 28 6 , 28C PAPIER TOAL 34663A 1 xl9, 98 19, 98A MIELONE 2 571950c 1 xl0 , 98 10 , 98C SANDWICH P 958560c 1 *5, 39 5 , 39C ORZES ZKI W 4 9235 9C 1   x3 , 99 3 , 99C CIASTO FRA 998924C 1 x5, 99 5 , 99c PASTA MAX F 5282 9A 1 x5, 61 5 , 61A SER MOZZAR 751976c 0 , 304 x33 , 89 10 , 30C AWOKADO 34067c 1  x2, 95 2 , 95C CHIPSY KET 521902c 1 x4, 99 4 , 99C 1 KRAJALNI 691060A 1 x8 , 99 8 , 99A ZIEMNIAK D 581227C 1 x8 , 98 8 , 98C SZAMPON WL 450850 1 xl6, 99 16 , 99A KAPUSTA BIA 27891c 1 , 538 x4 , 4 9 6 , 91c JAJA WOLNY 10372 9C 1 x7, 69 7, 69C BATON PAWE 502905A 1 x2 , 48 2 , 48A Rabat ORZESZKI W 4 92359C -0 80c
SPRZEDAŻ OPODATK . A PTU A 23 , 00 % SPRZEDAŻ OPODATK _ C PTU C 05 , 00 8 SUMA PTU SUMA PLN
61, 78 1l, 55 73 , 65 3 , 51 15, 0 6 135,43
#711 00000711 Karty plat
11 : 56 135, 43 PLN
Udzielono Łącznie rabatów : 0 , 8 0 Nr transakcji: 005 7 Kasa: 711 Kasjer:711
45124711000057030425
2025-05-23 20:30:01,151 - spizarnia - INFO - Odpowiedź modelu Bielik: Hnuchan HIPERMARKET AUCHAN 05-270 WARSZAWA MARKI AL J .PIŁSUDSKIEGO 1 TEL (0-22) 444 02 22 AUCHAN POLSKA SP_ 2 0 . 0 . UL PUŁAWSKA 4 6 , 05-500 PIASECZNO WWW auchan.pl BDO 000013917 NIP 526-03-09-174
NIEFISKALNY
2025-03-04 ReWtymOplRec551061
NAZWA;KATEGORIA;CENA;DATA_WAZNOCII
Napoje gazowe, 86851A;NIVELY;3,25 zł;PUSTY
Paroksy, JAL 32107c;LUBRICACJA;4,48 zł;PUSTY
Papier toaletowy, 34663A;MATERAC;l9,98 zł;PUSTY
Mielona, 2571950c;MIESZANKA;10,98 zł;PUSTY
Sandix, P 958560c;KARTOFEL;5,39 zł;1 marca 2025 r.
Orzech włoski, 492350c;MIĘSO;4,98 zł;PUSTY
Ciasto francuskie, F 998924c;MĄKA;5,99 zł;16 marca 2025 r.
Pasta Max F 5282;ZIARNO;6,17 zł;PUSTY
Ser mozzarella 751976c;MIĘSO;0,304 kg;PUSTY
Awokado, 34067c;KONSERWAT;2,95 zł;1 marca 2025 r.
Chipsy keto, 521902c;SZAMPON;4,99 zł;1 marca 2025 r.
Orzeszki włoskie, 691060A;SAŁATKA;8,99 zł;19 marca 2025 r.
Ziemniaki duszone, D 581227C;MĄKA;8,98 zł;PUSTY
Szampon w płynie, WL 450850;KOSMETYKA;16,99 zł;1 marca 2025 r.
Kapusta biała, 27891c;OLEJ Z GRZESIENIA;l,538 kg;PUSTY
Jaja wolno płynące, l0372;JAJA;7,69 kg;PUSTY
Baton pawe, 502905A;MITERAC;2,48 zł;1 marca 2025 r.
Rabat orzeszki włoskie, -0,80 zł;RABAT;PUSTY
2025-05-23 20:33:15,199 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:33:15,200 - spizarnia - INFO - Application started successfully
2025-05-23 20:34:11,562 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:34:11,563 - spizarnia - INFO - Application started successfully
2025-05-23 20:42:46,648 - spizarnia - INFO - Database tables created successfully
2025-05-23 20:42:46,648 - spizarnia - INFO - Application started successfully
2025-05-23 21:12:01,554 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:14:05,788 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:14:05,788 - spizarnia - INFO - Application started successfully
2025-05-23 21:15:04,319 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:15:04,319 - spizarnia - INFO - Application started successfully
2025-05-23 21:15:58,664 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:15:58,665 - spizarnia - INFO - Application started successfully
2025-05-23 21:17:38,322 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:17:38,322 - spizarnia - INFO - Application started successfully
2025-05-23 21:17:59,090 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:17:59,090 - spizarnia - INFO - Application started successfully
2025-05-23 21:20:33,848 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:20:33,848 - spizarnia - INFO - Application started successfully
2025-05-23 21:21:27,069 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:21:27,070 - spizarnia - INFO - Application started successfully
2025-05-23 21:22:18,211 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:22:18,212 - spizarnia - INFO - Application started successfully
2025-05-23 21:26:32,763 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:26:32,763 - spizarnia - INFO - Application started successfully
2025-05-23 21:27:00,880 - spizarnia - ERROR - Unexpected error adding receipt: Instance <Paragon at 0x75c7289c5da0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/routes/paragony.py", line 89, in dodaj_paragon
    asyncio.create_task(process_receipt_async(paragon.id))
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 1603, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Paragon at 0x75c7289c5da0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-05-23 21:29:25,713 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:29:25,713 - spizarnia - INFO - Application started successfully
2025-05-23 21:29:42,771 - spizarnia - ERROR - Unexpected error adding receipt: 'ReceiptProcessor' object has no attribute 'validate_and_save_file'
Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/routes/paragony.py", line 65, in dodaj_paragon
    saved_path = receipt_processor.validate_and_save_file(file)
AttributeError: 'ReceiptProcessor' object has no attribute 'validate_and_save_file'
2025-05-23 21:29:58,611 - spizarnia - ERROR - Unexpected error adding receipt: 'ReceiptProcessor' object has no attribute 'validate_and_save_file'
Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/routes/paragony.py", line 65, in dodaj_paragon
    saved_path = receipt_processor.validate_and_save_file(file)
AttributeError: 'ReceiptProcessor' object has no attribute 'validate_and_save_file'
2025-05-23 21:30:56,972 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:30:56,972 - spizarnia - INFO - Application started successfully
2025-05-23 21:31:08,457 - spizarnia - ERROR - Unexpected error adding receipt: OCZEKUJACY
Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/routes/paragony.py", line 74, in dodaj_paragon
    status_przetwarzania=StatusParagonu.OCZEKUJACY
  File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: OCZEKUJACY
2025-05-23 21:32:36,744 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:32:36,744 - spizarnia - INFO - Application started successfully
2025-05-23 21:33:30,617 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:33:30,617 - spizarnia - INFO - Application started successfully
2025-05-23 21:34:33,255 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:34:33,255 - spizarnia - INFO - Application started successfully
2025-05-23 21:46:00,077 - spizarnia - INFO - Database tables created successfully
2025-05-23 21:46:00,077 - spizarnia - INFO - Application started successfully
2025-05-23 22:26:43,742 - spizarnia - INFO - Database tables created successfully
2025-05-23 22:32:57,109 - spizarnia - INFO - Database tables created successfully
2025-05-23 22:32:57,109 - spizarnia - INFO - Database tables created successfully
2025-05-23 22:33:05,628 - spizarnia - INFO - Application started successfully
2025-05-23 22:33:05,628 - spizarnia - INFO - Application started successfully
2025-05-23 22:34:14,771 - spizarnia - INFO - Application started successfully
2025-05-23 22:34:14,771 - spizarnia - INFO - Application started successfully
2025-05-23 22:36:05,536 - spizarnia - INFO - Application started successfully
2025-05-23 22:36:05,536 - spizarnia - INFO - Application started successfully
2025-05-23 22:38:36,940 - spizarnia - INFO - Database tables created successfully
2025-05-23 22:38:46,456 - spizarnia - INFO - Application started successfully
2025-05-23 22:38:46,456 - spizarnia - INFO - Application started successfully
2025-05-23 22:41:31,706 - spizarnia - INFO - Application started successfully
2025-05-23 22:41:31,706 - spizarnia - INFO - Application started successfully
2025-05-23 22:46:23,888 - spizarnia - INFO - Application started successfully
2025-05-23 22:46:23,888 - spizarnia - INFO - Application started successfully
2025-05-23 22:48:13,797 - spizarnia - INFO - Application started successfully
2025-05-23 22:48:13,797 - spizarnia - INFO - Application started successfully
2025-05-23 22:51:19,811 - spizarnia - INFO - Application started successfully
2025-05-23 22:51:19,811 - spizarnia - INFO - Application started successfully
2025-05-23 22:54:37,165 - spizarnia - INFO - Application started successfully
2025-05-23 22:54:37,165 - spizarnia - INFO - Application started successfully
2025-05-23 22:56:10,532 - spizarnia - INFO - Application started successfully
2025-05-23 22:56:10,532 - spizarnia - INFO - Application started successfully
2025-05-23 22:56:32,149 - spizarnia - INFO - Application started successfully
2025-05-23 22:56:32,149 - spizarnia - INFO - Application started successfully
2025-05-24 06:13:22,164 - spizarnia - INFO - Database tables created successfully
2025-05-24 06:13:54,181 - spizarnia - INFO - Application started successfully
2025-05-24 06:13:54,181 - spizarnia - INFO - Application started successfully
2025-05-24 06:39:12,442 - spizarnia - INFO - Database tables created successfully
2025-05-24 06:39:45,523 - spizarnia - INFO - Application started successfully
2025-05-24 06:39:45,523 - spizarnia - INFO - Application started successfully
2025-05-24 06:39:52,451 - spizarnia - ERROR - Database session error: (sqlite3.OperationalError) no such column: produkt.status_mapowania
[SQL: SELECT produkt.id AS produkt_id, produkt.nazwa AS produkt_nazwa, produkt.kategoria AS produkt_kategoria, produkt.cena AS produkt_cena, produkt.data_waznosci AS produkt_data_waznosci, produkt.paragon_id AS produkt_paragon_id, produkt.data_dodania AS produkt_data_dodania, produkt.ilosc_na_paragonie AS produkt_ilosc_na_paragonie, produkt.aktualna_ilosc AS produkt_aktualna_ilosc, produkt.status_mapowania AS produkt_status_mapowania, produkt.sugestie_mapowania AS produkt_sugestie_mapowania, produkt.zmapowany_do_id AS produkt_zmapowany_do_id 
FROM produkt 
WHERE ? = produkt.paragon_id]
[parameters: (5,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: produkt.status_mapowania

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/database.py", line 40, in get_db_session
    yield session
  File "/home/marubo/PycharmProjects/webuiappgrocery/routes/paragony.py", line 294, in usun_paragon
    db.commit()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 442, in execute
    postsort_actions = self._generate_actions()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 400, in _generate_actions
    if action.execute(self):
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    self.dependency_processor.presort_deletes(uow, delete_states)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/dependency.py", line 450, in presort_deletes
    history = uowcommit.get_attribute_history(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 283, in get_attribute_history
    history = impl.get_history(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1679, in get_history
    current = self.get(state, dict_, passive=passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 978, in _load_for_state
    return self._emit_lazyload(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1141, in _emit_lazyload
    result = session.execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 127, in execute
    return super().execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: produkt.status_mapowania
[SQL: SELECT produkt.id AS produkt_id, produkt.nazwa AS produkt_nazwa, produkt.kategoria AS produkt_kategoria, produkt.cena AS produkt_cena, produkt.data_waznosci AS produkt_data_waznosci, produkt.paragon_id AS produkt_paragon_id, produkt.data_dodania AS produkt_data_dodania, produkt.ilosc_na_paragonie AS produkt_ilosc_na_paragonie, produkt.aktualna_ilosc AS produkt_aktualna_ilosc, produkt.status_mapowania AS produkt_status_mapowania, produkt.sugestie_mapowania AS produkt_sugestie_mapowania, produkt.zmapowany_do_id AS produkt_zmapowany_do_id 
FROM produkt 
WHERE ? = produkt.paragon_id]
[parameters: (5,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-24 06:39:52,451 - spizarnia - ERROR - Database session error: (sqlite3.OperationalError) no such column: produkt.status_mapowania
[SQL: SELECT produkt.id AS produkt_id, produkt.nazwa AS produkt_nazwa, produkt.kategoria AS produkt_kategoria, produkt.cena AS produkt_cena, produkt.data_waznosci AS produkt_data_waznosci, produkt.paragon_id AS produkt_paragon_id, produkt.data_dodania AS produkt_data_dodania, produkt.ilosc_na_paragonie AS produkt_ilosc_na_paragonie, produkt.aktualna_ilosc AS produkt_aktualna_ilosc, produkt.status_mapowania AS produkt_status_mapowania, produkt.sugestie_mapowania AS produkt_sugestie_mapowania, produkt.zmapowany_do_id AS produkt_zmapowany_do_id 
FROM produkt 
WHERE ? = produkt.paragon_id]
[parameters: (5,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: produkt.status_mapowania

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/database.py", line 40, in get_db_session
    yield session
  File "/home/marubo/PycharmProjects/webuiappgrocery/routes/paragony.py", line 294, in usun_paragon
    db.commit()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 442, in execute
    postsort_actions = self._generate_actions()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 400, in _generate_actions
    if action.execute(self):
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    self.dependency_processor.presort_deletes(uow, delete_states)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/dependency.py", line 450, in presort_deletes
    history = uowcommit.get_attribute_history(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 283, in get_attribute_history
    history = impl.get_history(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1679, in get_history
    current = self.get(state, dict_, passive=passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 978, in _load_for_state
    return self._emit_lazyload(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1141, in _emit_lazyload
    result = session.execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 127, in execute
    return super().execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: produkt.status_mapowania
[SQL: SELECT produkt.id AS produkt_id, produkt.nazwa AS produkt_nazwa, produkt.kategoria AS produkt_kategoria, produkt.cena AS produkt_cena, produkt.data_waznosci AS produkt_data_waznosci, produkt.paragon_id AS produkt_paragon_id, produkt.data_dodania AS produkt_data_dodania, produkt.ilosc_na_paragonie AS produkt_ilosc_na_paragonie, produkt.aktualna_ilosc AS produkt_aktualna_ilosc, produkt.status_mapowania AS produkt_status_mapowania, produkt.sugestie_mapowania AS produkt_sugestie_mapowania, produkt.zmapowany_do_id AS produkt_zmapowany_do_id 
FROM produkt 
WHERE ? = produkt.paragon_id]
[parameters: (5,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-24 06:40:01,323 - spizarnia - ERROR - Database session error: (sqlite3.OperationalError) no such column: produkt.status_mapowania
[SQL: SELECT produkt.id AS produkt_id, produkt.nazwa AS produkt_nazwa, produkt.kategoria AS produkt_kategoria, produkt.cena AS produkt_cena, produkt.data_waznosci AS produkt_data_waznosci, produkt.paragon_id AS produkt_paragon_id, produkt.data_dodania AS produkt_data_dodania, produkt.ilosc_na_paragonie AS produkt_ilosc_na_paragonie, produkt.aktualna_ilosc AS produkt_aktualna_ilosc, produkt.status_mapowania AS produkt_status_mapowania, produkt.sugestie_mapowania AS produkt_sugestie_mapowania, produkt.zmapowany_do_id AS produkt_zmapowany_do_id 
FROM produkt 
WHERE ? = produkt.paragon_id]
[parameters: (4,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: produkt.status_mapowania

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/database.py", line 40, in get_db_session
    yield session
  File "/home/marubo/PycharmProjects/webuiappgrocery/routes/paragony.py", line 294, in usun_paragon
    db.commit()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 442, in execute
    postsort_actions = self._generate_actions()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 400, in _generate_actions
    if action.execute(self):
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    self.dependency_processor.presort_deletes(uow, delete_states)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/dependency.py", line 450, in presort_deletes
    history = uowcommit.get_attribute_history(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 283, in get_attribute_history
    history = impl.get_history(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1679, in get_history
    current = self.get(state, dict_, passive=passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 978, in _load_for_state
    return self._emit_lazyload(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1141, in _emit_lazyload
    result = session.execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 127, in execute
    return super().execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: produkt.status_mapowania
[SQL: SELECT produkt.id AS produkt_id, produkt.nazwa AS produkt_nazwa, produkt.kategoria AS produkt_kategoria, produkt.cena AS produkt_cena, produkt.data_waznosci AS produkt_data_waznosci, produkt.paragon_id AS produkt_paragon_id, produkt.data_dodania AS produkt_data_dodania, produkt.ilosc_na_paragonie AS produkt_ilosc_na_paragonie, produkt.aktualna_ilosc AS produkt_aktualna_ilosc, produkt.status_mapowania AS produkt_status_mapowania, produkt.sugestie_mapowania AS produkt_sugestie_mapowania, produkt.zmapowany_do_id AS produkt_zmapowany_do_id 
FROM produkt 
WHERE ? = produkt.paragon_id]
[parameters: (4,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-24 06:40:01,323 - spizarnia - ERROR - Database session error: (sqlite3.OperationalError) no such column: produkt.status_mapowania
[SQL: SELECT produkt.id AS produkt_id, produkt.nazwa AS produkt_nazwa, produkt.kategoria AS produkt_kategoria, produkt.cena AS produkt_cena, produkt.data_waznosci AS produkt_data_waznosci, produkt.paragon_id AS produkt_paragon_id, produkt.data_dodania AS produkt_data_dodania, produkt.ilosc_na_paragonie AS produkt_ilosc_na_paragonie, produkt.aktualna_ilosc AS produkt_aktualna_ilosc, produkt.status_mapowania AS produkt_status_mapowania, produkt.sugestie_mapowania AS produkt_sugestie_mapowania, produkt.zmapowany_do_id AS produkt_zmapowany_do_id 
FROM produkt 
WHERE ? = produkt.paragon_id]
[parameters: (4,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: produkt.status_mapowania

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marubo/PycharmProjects/webuiappgrocery/database.py", line 40, in get_db_session
    yield session
  File "/home/marubo/PycharmProjects/webuiappgrocery/routes/paragony.py", line 294, in usun_paragon
    db.commit()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 442, in execute
    postsort_actions = self._generate_actions()
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 400, in _generate_actions
    if action.execute(self):
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    self.dependency_processor.presort_deletes(uow, delete_states)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/dependency.py", line 450, in presort_deletes
    history = uowcommit.get_attribute_history(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 283, in get_attribute_history
    history = impl.get_history(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1679, in get_history
    current = self.get(state, dict_, passive=passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 978, in _load_for_state
    return self._emit_lazyload(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1141, in _emit_lazyload
    result = session.execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 127, in execute
    return super().execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/marubo/PycharmProjects/webuiappgrocery/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: produkt.status_mapowania
[SQL: SELECT produkt.id AS produkt_id, produkt.nazwa AS produkt_nazwa, produkt.kategoria AS produkt_kategoria, produkt.cena AS produkt_cena, produkt.data_waznosci AS produkt_data_waznosci, produkt.paragon_id AS produkt_paragon_id, produkt.data_dodania AS produkt_data_dodania, produkt.ilosc_na_paragonie AS produkt_ilosc_na_paragonie, produkt.aktualna_ilosc AS produkt_aktualna_ilosc, produkt.status_mapowania AS produkt_status_mapowania, produkt.sugestie_mapowania AS produkt_sugestie_mapowania, produkt.zmapowany_do_id AS produkt_zmapowany_do_id 
FROM produkt 
WHERE ? = produkt.paragon_id]
[parameters: (4,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-24 06:42:29,668 - spizarnia - INFO - Application started successfully
2025-05-24 06:42:29,668 - spizarnia - INFO - Application started successfully
